package com.rs.game.content.leagues;

public enum LeaguesTask {

	FIRST_LEVEL_UP(10, "Achieve Your First Level Up", "Level up any of your skills for the first time.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_5(10, "Achieve Your First Level 5", "Reach level 5 in any skill (not including Agility, Hitpoints, and Runecraft).", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_10(10, "Achieve Your First Level 10", "Reach level 10 in any skill (not including Agility, Hitpoints).", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_20(10, "Achieve Your First Level 20", "Reach level 20 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_30(40, "Achieve Your First Level 30", "Reach level 30 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_40(40, "Achieve Your First Level 40", "Reach level 40 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_50(40, "Achieve Your First Level 50", "Reach level 50 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_60(80, "Achieve Your First Level 60", "Reach level 60 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_70(80, "Achieve Your First Level 70", "Reach level 70 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_80(80, "Achieve Your First Level 80", "Reach level 80 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_90(200, "Achieve Your First Level 90", "Reach level 90 in any skill.", LeaguesRegion.GLOBAL),
	ACHIEVE_FIRST_LEVEL_95(200, "Achieve Your First Level 95", "Reach level 95 in any skill.", LeaguesRegion.GLOBAL),
	REACH_99_AGILITY(200, "Reach Level 99 Agility", "Reach level 99 in your Agility skill.", LeaguesRegion.GLOBAL),
	REACH_99_ATTACK(200, "Reach Level 99 Attack", "Reach level 99 in your Attack skill.", LeaguesRegion.GLOBAL),
	REACH_99_CONSTRUCTION(200, "Reach Level 99 Construction", "Reach level 99 in your Construction skill.", LeaguesRegion.GLOBAL),
	REACH_99_COOKING(200, "Reach Level 99 Cooking", "Reach level 99 in your Cooking skill.", LeaguesRegion.GLOBAL),
	REACH_99_CRAFTING(200, "Reach Level 99 Crafting", "Reach level 99 in your Crafting skill.", LeaguesRegion.GLOBAL),
	REACH_99_DEFENCE(200, "Reach Level 99 Defence", "Reach level 99 in your Defence skill.", LeaguesRegion.GLOBAL),
	REACH_99_FARMING(200, "Reach Level 99 Farming", "Reach level 99 in your Farming skill.", LeaguesRegion.GLOBAL),
	REACH_99_FIREMAKING(200, "Reach Level 99 Firemaking", "Reach level 99 in your Firemaking skill.", LeaguesRegion.GLOBAL),
	REACH_99_FISHING(200, "Reach Level 99 Fishing", "Reach level 99 in your Fishing skill.", LeaguesRegion.GLOBAL),
	REACH_99_FLETCHING(200, "Reach Level 99 Fletching", "Reach level 99 in your Fletching skill.", LeaguesRegion.GLOBAL),
	REACH_99_HERBLORE(200, "Reach Level 99 Herblore", "Reach level 99 in your Herblore skill.", LeaguesRegion.GLOBAL),
	REACH_99_HITPOINTS(200, "Reach Level 99 Hitpoints", "Reach level 99 in your Hitpoints skill.", LeaguesRegion.GLOBAL),
	REACH_99_HUNTER(200, "Reach Level 99 Hunter", "Reach level 99 in your Hunter skill.", LeaguesRegion.GLOBAL),
	REACH_99_MAGIC(200, "Reach Level 99 Magic", "Reach level 99 in your Magic skill.", LeaguesRegion.GLOBAL),
	REACH_99_MINING(200, "Reach Level 99 Mining", "Reach level 99 in your Mining skill.", LeaguesRegion.GLOBAL),
	REACH_99_PRAYER(200, "Reach Level 99 Prayer", "Reach level 99 in your Prayer skill.", LeaguesRegion.GLOBAL),
	REACH_99_RANGED(200, "Reach Level 99 Ranged", "Reach level 99 in your Ranged skill.", LeaguesRegion.GLOBAL),
	REACH_99_RUNECRAFTING(200, "Reach Level 99 Runecrafting", "Reach level 99 in your Runecrafting skill.", LeaguesRegion.GLOBAL),
	REACH_99_SLAYER(200, "Reach Level 99 Slayer", "Reach level 99 in your Slayer skill.", LeaguesRegion.GLOBAL),
	REACH_99_SMITHING(200, "Reach Level 99 Smithing", "Reach level 99 in your Smithing skill.", LeaguesRegion.GLOBAL),
	REACH_99_STRENGTH(200, "Reach Level 99 Strength", "Reach level 99 in your Strength skill.", LeaguesRegion.GLOBAL),
	REACH_99_THIEVING(200, "Reach Level 99 Thieving", "Reach level 99 in your Thieving skill.", LeaguesRegion.GLOBAL),
	REACH_99_WOODCUTTING(200, "Reach Level 99 Woodcutting", "Reach level 99 in your Woodcutting skill.", LeaguesRegion.GLOBAL),
	REACH_99_SUMMONING(200, "Reach Level 99 Summoning", "Reach level 99 in your Summoning skill.", LeaguesRegion.GLOBAL),
	REACH_99_DUNGEONEERING(200, "Reach Level 99 Dungeoneering", "Reach level 99 in your Dungeoneering skill.", LeaguesRegion.GLOBAL),
	REACH_120_DUNGEONEERING(400, "Reach Level 120 Dungeoneering", "Reach level 120 in your Dungeoneering skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_AGILITY(200, "Obtain 25 Million Agility XP", "Obtain 25 Million XP in your Agility skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_ATTACK(200, "Obtain 25 Million Attack XP", "Obtain 25 Million XP in your Attack skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_CONSTRUCTION(200, "Obtain 25 Million Construction XP", "Obtain 25 Million XP in your Construction skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_COOKING(200, "Obtain 25 Million Cooking XP", "Obtain 25 Million XP in your Cooking skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_CRAFTING(200, "Obtain 25 Million Crafting XP", "Obtain 25 Million XP in your Crafting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_DEFENCE(200, "Obtain 25 Million Defence XP", "Obtain 25 Million XP in your Defence skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_FARMING(200, "Obtain 25 Million Farming XP", "Obtain 25 Million XP in your Farming skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_FIREMAKING(200, "Obtain 25 Million Firemaking XP", "Obtain 25 Million XP in your Firemaking skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_FISHING(200, "Obtain 25 Million Fishing XP", "Obtain 25 Million XP in your Fishing skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_FLETCHING(200, "Obtain 25 Million Fletching XP", "Obtain 25 Million XP in your Fletching skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_HERBLORE(200, "Obtain 25 Million Herblore XP", "Obtain 25 Million XP in your Herblore skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_HITPOINTS(200, "Obtain 25 Million Hitpoints XP", "Obtain 25 Million XP in your Hitpoints skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_HUNTER(200, "Obtain 25 Million Hunter XP", "Obtain 25 Million XP in your Hunter skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_MAGIC(200, "Obtain 25 Million Magic XP", "Obtain 25 Million XP in your Magic skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_MINING(200, "Obtain 25 Million Mining XP", "Obtain 25 Million XP in your Mining skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_PRAYER(200, "Obtain 25 Million Prayer XP", "Obtain 25 Million XP in your Prayer skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_RANGED(200, "Obtain 25 Million Ranged XP", "Obtain 25 Million XP in your Ranged skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_RUNECRAFTING(200, "Obtain 25 Million Runecrafting XP", "Obtain 25 Million XP in your Runecrafting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_SLAYER(200, "Obtain 25 Million Slayer XP", "Obtain 25 Million XP in your Slayer skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_SMITHING(200, "Obtain 25 Million Smithing XP", "Obtain 25 Million XP in your Smithing skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_STRENGTH(200, "Obtain 25 Million Strength XP", "Obtain 25 Million XP in your Strength skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_THIEVING(200, "Obtain 25 Million Thieving XP", "Obtain 25 Million XP in your Thieving skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_WOODCUTTING(200, "Obtain 25 Million Woodcutting XP", "Obtain 25 Million XP in your Woodcutting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_SUMMONING(200, "Obtain 25 Million Summoning XP", "Obtain 25 Million XP in your Summoning skill.", LeaguesRegion.GLOBAL),
	OBTAIN_25M_DUNGEONEERING(200, "Obtain 25 Million Dungeoneering XP", "Obtain 25 Million XP in your Dungeoneering skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_AGILITY(200, "Obtain 35 Million Agility XP", "Obtain 35 Million XP in your Agility skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_ATTACK(200, "Obtain 35 Million Attack XP", "Obtain 35 Million XP in your Attack skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_CONSTRUCTION(200, "Obtain 35 Million Construction XP", "Obtain 35 Million XP in your Construction skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_COOKING(200, "Obtain 35 Million Cooking XP", "Obtain 35 Million XP in your Cooking skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_CRAFTING(200, "Obtain 35 Million Crafting XP", "Obtain 35 Million XP in your Crafting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_DEFENCE(200, "Obtain 35 Million Defence XP", "Obtain 35 Million XP in your Defence skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_FARMING(200, "Obtain 35 Million Farming XP", "Obtain 35 Million XP in your Farming skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_FIREMAKING(200, "Obtain 35 Million Firemaking XP", "Obtain 35 Million XP in your Firemaking skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_FISHING(200, "Obtain 35 Million Fishing XP", "Obtain 35 Million XP in your Fishing skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_FLETCHING(200, "Obtain 35 Million Fletching XP", "Obtain 35 Million XP in your Fletching skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_HERBLORE(200, "Obtain 35 Million Herblore XP", "Obtain 35 Million XP in your Herblore skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_HITPOINTS(200, "Obtain 35 Million Hitpoints XP", "Obtain 35 Million XP in your Hitpoints skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_HUNTER(200, "Obtain 35 Million Hunter XP", "Obtain 35 Million XP in your Hunter skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_MAGIC(200, "Obtain 35 Million Magic XP", "Obtain 35 Million XP in your Magic skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_MINING(200, "Obtain 35 Million Mining XP", "Obtain 35 Million XP in your Mining skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_PRAYER(200, "Obtain 35 Million Prayer XP", "Obtain 35 Million XP in your Prayer skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_RANGED(200, "Obtain 35 Million Ranged XP", "Obtain 35 Million XP in your Ranged skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_RUNECRAFTING(200, "Obtain 35 Million Runecrafting XP", "Obtain 35 Million XP in your Runecrafting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_SLAYER(200, "Obtain 35 Million Slayer XP", "Obtain 35 Million XP in your Slayer skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_SMITHING(200, "Obtain 35 Million Smithing XP", "Obtain 35 Million XP in your Smithing skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_STRENGTH(200, "Obtain 35 Million Strength XP", "Obtain 35 Million XP in your Strength skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_THIEVING(200, "Obtain 35 Million Thieving XP", "Obtain 35 Million XP in your Thieving skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_WOODCUTTING(200, "Obtain 35 Million Woodcutting XP", "Obtain 35 Million XP in your Woodcutting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_SUMMONING(200, "Obtain 35 Million Summoning XP", "Obtain 35 Million XP in your Summoning skill.", LeaguesRegion.GLOBAL),
	OBTAIN_35M_DUNGEONEERING(200, "Obtain 35 Million Dungeoneering XP", "Obtain 35 Million XP in your Dungeoneering skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_AGILITY(200, "Obtain 50 Million Agility XP", "Obtain 50 Million XP in your Agility skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_ATTACK(200, "Obtain 50 Million Attack XP", "Obtain 50 Million XP in your Attack skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_CONSTRUCTION(200, "Obtain 50 Million Construction XP", "Obtain 50 Million XP in your Construction skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_COOKING(200, "Obtain 50 Million Cooking XP", "Obtain 50 Million XP in your Cooking skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_CRAFTING(200, "Obtain 50 Million Crafting XP", "Obtain 50 Million XP in your Crafting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_DEFENCE(200, "Obtain 50 Million Defence XP", "Obtain 50 Million XP in your Defence skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_FARMING(200, "Obtain 50 Million Farming XP", "Obtain 50 Million XP in your Farming skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_FIREMAKING(200, "Obtain 50 Million Firemaking XP", "Obtain 50 Million XP in your Firemaking skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_FISHING(200, "Obtain 50 Million Fishing XP", "Obtain 50 Million XP in your Fishing skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_FLETCHING(200, "Obtain 50 Million Fletching XP", "Obtain 50 Million XP in your Fletching skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_HERBLORE(200, "Obtain 50 Million Herblore XP", "Obtain 50 Million XP in your Herblore skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_HITPOINTS(200, "Obtain 50 Million Hitpoints XP", "Obtain 50 Million XP in your Hitpoints skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_HUNTER(200, "Obtain 50 Million Hunter XP", "Obtain 50 Million XP in your Hunter skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_MAGIC(200, "Obtain 50 Million Magic XP", "Obtain 50 Million XP in your Magic skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_MINING(200, "Obtain 50 Million Mining XP", "Obtain 50 Million XP in your Mining skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_PRAYER(200, "Obtain 50 Million Prayer XP", "Obtain 50 Million XP in your Prayer skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_RANGED(200, "Obtain 50 Million Ranged XP", "Obtain 50 Million XP in your Ranged skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_RUNECRAFTING(200, "Obtain 50 Million Runecrafting XP", "Obtain 50 Million XP in your Runecrafting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_SLAYER(200, "Obtain 50 Million Slayer XP", "Obtain 50 Million XP in your Slayer skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_SMITHING(200, "Obtain 50 Million Smithing XP", "Obtain 50 Million XP in your Smithing skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_STRENGTH(200, "Obtain 50 Million Strength XP", "Obtain 50 Million XP in your Strength skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_THIEVING(200, "Obtain 50 Million Thieving XP", "Obtain 50 Million XP in your Thieving skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_WOODCUTTING(200, "Obtain 50 Million Woodcutting XP", "Obtain 50 Million XP in your Woodcutting skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_SUMMONING(200, "Obtain 50 Million Summoning XP", "Obtain 50 Million XP in your Summoning skill.", LeaguesRegion.GLOBAL),
	OBTAIN_50M_DUNGEONEERING(200, "Obtain 50 Million Dungeoneering XP", "Obtain 50 Million XP in your Dungeoneering skill.", LeaguesRegion.GLOBAL),



	REACH_TOTAL_LEVEL_100(10, "Reach Total Level 100", "Reach a Total Level of 100.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_200(10, "Reach Total Level 200", "Reach a Total Level of 200.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_500(10, "Reach Total Level 500", "Reach a Total Level of 500.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_750(40, "Reach Total Level 750", "Reach a Total Level of 750.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_1000(40, "Reach Total Level 1000", "Reach a Total Level of 1000.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_1250(40, "Reach Total Level 1250", "Reach a Total Level of 1250.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_1500(80, "Reach Total Level 1500", "Reach a Total Level of 1500.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_1750(80, "Reach Total Level 1750", "Reach a Total Level of 1750.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_2000(200, "Reach Total Level 2000", "Reach a Total Level of 2000.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_2100(200, "Reach Total Level 2100", "Reach a Total Level of 2100.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_2200(200, "Reach Total Level 2200", "Reach a Total Level of 2200.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_2300(200, "Reach Total Level 2300", "Reach a Total Level of 2300.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_2400(200, "Reach Total Level 2400", "Reach a Total Level of 2400.", LeaguesRegion.GLOBAL),
	REACH_TOTAL_LEVEL_2496(400, "Reach Total Level 2496", "Reach a Total Level of 2496.", LeaguesRegion.GLOBAL),

	REACH_COMBAT_LEVEL_10(10, "Reach Combat Level 10", "Reach Combat Level 10.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_25(10, "Reach Combat Level 25", "Reach Combat Level 25.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_50(40, "Reach Combat Level 50", "Reach Combat Level 50.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_75(40, "Reach Combat Level 75", "Reach Combat Level 75.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_100(80, "Reach Combat Level 100", "Reach Combat Level 100.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_110(80, "Reach Combat Level 110", "Reach Combat Level 110.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_120(200, "Reach Combat Level 120", "Reach Combat Level 120.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_126(200, "Reach Combat Level 126", "Reach Combat Level 126.", LeaguesRegion.GLOBAL),
	REACH_COMBAT_LEVEL_138(400, "Reach Combat Level 138", "Reach Combat Level 138.", LeaguesRegion.GLOBAL),

	REACH_BASE_LEVEL_5(10, "Reach Base Level 5", "Reach level 5 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_10(10, "Reach Base Level 10", "Reach level 10 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_20(10, "Reach Base Level 20", "Reach level 20 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_30(40, "Reach Base Level 30", "Reach level 30 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_40(40, "Reach Base Level 40", "Reach level 40 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_50(40, "Reach Base Level 50", "Reach level 50 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_60(80, "Reach Base Level 60", "Reach level 60 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_70(80, "Reach Base Level 70", "Reach level 70 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_80(200, "Reach Base Level 80", "Reach level 80 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_90(200, "Reach Base Level 90", "Reach level 90 in every skill.", LeaguesRegion.GLOBAL),
	REACH_BASE_LEVEL_95(400, "Reach Base Level 95", "Reach level 95 in every skill.", LeaguesRegion.GLOBAL),

	OPEN_EASY_CLUE(10, "1 Easy Clue Scroll", "Open a Reward Casket for completing an easy clue scroll.", LeaguesRegion.GLOBAL),
	OPEN_MEDIUM_CLUE(10, "1 Medium Clue Scroll", "Open a Reward Casket for completing a medium clue scroll.", LeaguesRegion.GLOBAL),
	OPEN_25_EASY_CLUE(10, "25 Easy Clue Scrolls", "Open 25 Reward Caskets for completing easy clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_25_MEDIUM_CLUE(10, "25 Medium Clue Scrolls", "Open 25 Reward Caskets for completing medium clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_HARD_CLUE(40, "1 Hard Clue Scroll", "Open a Reward Casket for completing a hard clue scroll.", LeaguesRegion.GLOBAL),
	OPEN_ELITE_CLUE(40, "1 Elite Clue Scroll", "Open a Reward Casket for completing an elite clue scroll.", LeaguesRegion.GLOBAL),
	OPEN_75_EASY_CLUE(40, "75 Easy Clue Scrolls", "Open 75 Reward Caskets for completing easy clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_150_EASY_CLUE(40, "150 Easy Clue Scrolls", "Open 150 Reward Caskets for completing easy clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_75_MEDIUM_CLUE(40, "75 Medium Clue Scrolls", "Open 75 Reward Caskets for completing medium clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_150_MEDIUM_CLUE(40, "150 Medium Clue Scrolls", "Open 150 Reward Caskets for completing medium clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_25_HARD_CLUE(40, "25 Hard Clue Scrolls", "Open 25 Reward Caskets for completing hard clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_75_HARD_CLUE(80, "75 Hard Clue Scrolls", "Open 75 Reward Caskets for completing hard clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_150_HARD_CLUE(80, "150 Hard Clue Scrolls", "Open 150 Reward Caskets for completing hard clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_25_ELITE_CLUE(80, "25 Elite Clue Scrolls", "Open 25 Reward Caskets for completing elite clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_75_ELITE_CLUE(80, "75 Elite Clue Scrolls", "Open 75 Reward Caskets for completing elite clue scrolls.", LeaguesRegion.GLOBAL),
	OPEN_150_ELITE_CLUE(80, "150 Elite Clue Scrolls", "Open 150 Reward Caskets for completing elite clue scrolls.", LeaguesRegion.GLOBAL),

	BURN_FOOD(10, "Burn Some Food", "Burn any kind of food while trying to cook it.", LeaguesRegion.GLOBAL),
	COOK_5_PIECES(10, "Successfully Cook 5 Pieces of Food", "Cook 5 pieces of food in a row without burning them.", LeaguesRegion.GLOBAL, 0),
	LODESTONE_TELEPORT(10, "Cast Lodestone Teleport", "Teleport using the lodestone network.", LeaguesRegion.GLOBAL),
	BURY_BONES(10, "Bury Some Bones", "Bury any kind of bones.", LeaguesRegion.GLOBAL),
	BURY_DRAGON_BONES(40, "Bury Some Wyvern or Dragon Bones", "Bury either some Wyvern Bones or some Dragon Bones.", LeaguesRegion.GLOBAL),
	BURN_NORMAL(10, "Burn Some Normal Logs", "Burn some Normal Logs.", LeaguesRegion.GLOBAL),
	BURN_OAK(10, "Burn Some Oak Logs", "Burn some Oak Logs.", LeaguesRegion.GLOBAL),
	BURN_100_WILLOW(40, "Burn 100 Willow Logs", "Burn 100 Willow Logs.", LeaguesRegion.GLOBAL, 0),
	BURN_100_YEW(80, "Burn 100 Yew Logs", "Burn 100 Yew Logs.", LeaguesRegion.GLOBAL, 0),
	BURN_MAGIC(80, "Burn Some Magic Logs", "Burn some Magic Logs.", LeaguesRegion.GLOBAL),
	CHECK_SLAYER_TASK(10, "Check Your Slayer Task", "Use an Enchanted Gem to check your Slayer Task.", LeaguesRegion.GLOBAL),
	CHOP_SOME_LOGS(10, "Chop Some Logs", "Chop any kind of logs.", LeaguesRegion.GLOBAL),
	CHOP_LOGS_WITH_STEEL(10, "Chop Some Logs With a Steel Hatchet", "Chop any kind of logs using a Steel Hatchet.", LeaguesRegion.GLOBAL),
	CHOP_LOGS_WITH_RUNE(40, "Chop Some Logs With a Rune Hatchet", "Chop any kind of logs using a Rune Hatchet.", LeaguesRegion.GLOBAL),
	CHOP_100_WILLOW(40, "Chop 100 Willow Logs", "Chop 100 Willow Logs from Willow Trees.", LeaguesRegion.GLOBAL, 0),
	CHOP_75_MAGIC(80, "Chop 75 Magic Logs", "Chop 75 Magic Logs from Magic Trees.", LeaguesRegion.GLOBAL, 0),
	CATCH_HERRING(10, "Catch a Herring", "Catch a Raw Herring whilst Fishing.", LeaguesRegion.GLOBAL),
	CATCH_SHRIMP(10, "Catch a Shrimp", "Catch a Raw Shrimp whilst Fishing.", LeaguesRegion.GLOBAL),
	CATCH_ANCHOVY(10, "Catch an Anchovy", "Catch a Raw Anchovy whilst Fishing.", LeaguesRegion.GLOBAL),
	BUY_TRADER_CREWMEMBER(10, "Buy Something From Trader Crewmembers", "Buy something from the Trader Crewmembers.", LeaguesRegion.GLOBAL),
	CLEAN_GUAM(10, "Clean a Grimy Guam", "Clean a Grimy Guam.", LeaguesRegion.GLOBAL),
	COMPLETE_SLAYER_TASK(10, "Complete 1 Slayer Task", "Complete 1 Slayer Task.", LeaguesRegion.GLOBAL),
	COOK_SHRIMP(10, "Cook Shrimp", "Cook Raw Shrimp.", LeaguesRegion.GLOBAL),

	CRAFT_RUNE(10, "Craft Any Rune", "Use a Runecrafting Altar to craft any type of rune from Essence.", LeaguesRegion.GLOBAL),
	CREATE_ANTIPOISON(10, "Create an Antipoison", "Create an Antipoison.", LeaguesRegion.GLOBAL),
	CUT_SAPPHIRE(10, "Cut a Sapphire", "Cut a Sapphire.", LeaguesRegion.GLOBAL),
	KILL_GOBLIN(10, "Defeat a Goblin", "Defeat a Goblin.", LeaguesRegion.GLOBAL),
	KILL_GUARD(10, "Defeat a Guard", "Defeat a Guard.", LeaguesRegion.GLOBAL),
	KILL_MOSS_GIANT(10, "Defeat a Moss Giant", "Defeat a Moss Giant.", LeaguesRegion.GLOBAL),
	DRINK_STRENGTH_POTION(10, "Drink a Strength Potion", "Drink a Strength Potion.", LeaguesRegion.GLOBAL),
	EQUIP_MITHRIL_SET(10, "Equip a Full Mithril Set", "Equip a Mithril Platebody, a Mithril Full Helm, and either some Mithril Platelegs or a Mithril Plateskirt.", LeaguesRegion.GLOBAL),
	EQUIP_SOME_BLACK_ARMOUR(10, "Equip Some Black Armour", "Equip either a Black Platebody, some Black Platelegs, a Black Plateskirt, or a Black Full Helm.", LeaguesRegion.GLOBAL),
	EQUIP_SOME_STEEL_ARMOUR(10, "Equip Some Steel Armour", "Equip either a Steel Platebody, some Steel Platelegs, a Steel Plateskirt, or a Steel Full Helm.", LeaguesRegion.GLOBAL),
	EQUIP_ADAMANT_SET(40, "Equip a Full Adamant Set", "Equip an Adamant Platebody, an Adamant Full Helm, and either some Adamant Platelegs or an Adamant Plateskirt.", LeaguesRegion.GLOBAL),
	EQUIP_RUNE_SET(40, "Equip a Full Rune Set", "Equip a Rune Platebody, a Rune Full Helm, and either some Rune Platelegs or a Rune Plateskirt.", LeaguesRegion.GLOBAL),
	EQUIP_BLUE_DRAGONHIDE_SET(40, "Equip a Full Blue Dragonhide Set", "Equip a Blue Dragonhide Body, some Blue Dragonhide Chaps, and some Blue Dragonhide Vambraces", LeaguesRegion.GLOBAL),
	EQUIP_GREEN_DRAGONHIDE_SET(40, "Equip a Full Green Dragonhide Set", "Equip a Green Dragonhide Body, some Green Dragonhide Chaps, and some Green Dragonhide Vambraces", LeaguesRegion.GLOBAL),
	EQUIP_RED_DRAGONHIDE_SET(40, "Equip a Full Red Dragonhide Set", "Equip a Red Dragonhide Body, some Red Dragonhide Chaps, and some Red Dragonhide Vambraces", LeaguesRegion.GLOBAL),
	EQUIP_FULL_GRAAHK(40, "Equip Full Graahk, Larupia, or Kyatt", "Equip a full set of Graahk, Larupia, or Kyatt attire.", LeaguesRegion.GLOBAL),
	EQUIP_LAVA_BATTLESTAFF(40, "Equip a Lava Battlestaff", "Equip a Lava Battlestaff.", LeaguesRegion.GLOBAL),
	EQUIP_LEAF_BLADED_SWORD(40, "Equip a Leaf-Bladed Sword", "Equip a Leaf-Bladed Sword.", LeaguesRegion.GLOBAL),
	EQUIP_SOME_MYSTIC(40, "Equip a Piece of a Mystic Set", "Equip any piece of any Mystic robe set.", LeaguesRegion.GLOBAL),
	EQUIP_WIZARD_ROBE_HAT(40, "Equip a Wizard Robe and Hat", "Equip any wizard robe along with any wizard hat.", LeaguesRegion.GLOBAL),
	EQUIP_HARPIE_LANTERN(40, "Equip a Harpie Bug Lantern", "Equip a Harpie Bug Lantern.", LeaguesRegion.GLOBAL),
	EQUIP_FROG_MASK(40, "Equip a Frog Mask", "Equip a Frog Mask.", LeaguesRegion.GLOBAL),
	EQUIP_YEW_SHORTBOW(40, "Equip a Yew Shortbow", "Equip a Yew Shortbow.", LeaguesRegion.GLOBAL),
	EQUIP_ADAMANT_WEAPON(40, "Equip a Main-hand Adamant Weapon", "Equip any main-hand Adamant Weapon.", LeaguesRegion.GLOBAL),
	EQUIP_RUNE_WEAPON(40, "Equip a Main-hand Rune Weapon", "Equip any main-hand Rune Weapon.", LeaguesRegion.GLOBAL),
	DEFEAT_CHROMATIC_DRAGON(40, "Defeat an Adult Chromatic Dragon", "Defeat either an adult Green Dragon, Blue Dragon, Red Dragon, or Black Dragon.", LeaguesRegion.GLOBAL),
	EQUIP_TRIMMED_AMULET(40, "Equip a Trimmed Amulet", "Equip a trimmed amulet", LeaguesRegion.GLOBAL),
	EQUIP_BATTLESTAFF_MYSTIC_STAFF(40, "Equip an Elemental Battlestaff or Mystic Staff", "Equip either an Elemental Battlestaff or a Mystic Staff.", LeaguesRegion.GLOBAL),
	CRAFT_LEATHER_BODY(10, "Craft a Leather Body", "Craft a Leather Body.", LeaguesRegion.GLOBAL),
	EAT_PURPLE_SWEETS(10, "Eat some Purple Sweets", "Eat some Purple Sweets.", LeaguesRegion.GLOBAL),
	ENTER_OWN_HOUSE(10, "Enter your Player Owned House", "Enter your Player Owned House.", LeaguesRegion.GLOBAL),
	EQUIP_MAPLE_SHORTBOW(10, "Equip a Maple Shortbow", "Equip a Maple Shortbow.", LeaguesRegion.GLOBAL),
	EQUIP_MITHRIL_WEAPON(10, "Equip a Main-hand Mithril Weapon", "Equip any main-hand Mithril Weapon.", LeaguesRegion.GLOBAL),
	EQUIP_SPINY_HELMET(10, "Equip a Spiny Helmet", "Equip a Spiny Helmet.", LeaguesRegion.GLOBAL),
	EQUIP_STUDDED_BODY_CHAPS(10, "Equip a Studded Body and Chaps", "Equip a Studded Body along with some Studded Chaps.", LeaguesRegion.GLOBAL),
	EQUIP_ELEMENTAL_STAFF(10, "Equip an Elemental Staff", "Equip a basic Elemental Staff.", LeaguesRegion.GLOBAL),
	EQUIP_COMBINATION_STAFF(80, "Equip a Combination Battlestaff or Mystic Staff", "Equip either a Combination Battlestaff or a Combination Mystic Staff.", LeaguesRegion.GLOBAL),
	EQUIP_DRAGON_WEAPON(80, "Equip a Dragon Weapon", "Equip any Dragon Weapon.", LeaguesRegion.GLOBAL),
	EQUIP_BLACK_DRAGONHIDE_SET(80, "Equip a Full Black Dragonhide Set", "Equip a Black Dragonhide Body, some Black Dragonhide Chaps, and some Black Dragonhide Vambraces", LeaguesRegion.GLOBAL),
	EQUIP_GILDED_TRIMMED_WIZARD_SET(80, "Equip a Full Gilded or Trimmed Wizard Set", "Equip a full set of Gilded Wizard Robes, or a full set of Trimmed Wizard Robes.", LeaguesRegion.GLOBAL),
	EQUIP_MAGIC_SHORTBOW(80, "Equip a Magic Shortbow", "Equip a Magic Shortbow.", LeaguesRegion.GLOBAL),
	EQUIP_RUNE_CROSSBOW(80, "Equip a Rune Crossbow", "Equip a Rune Crossbow.", LeaguesRegion.GLOBAL),
	EQUIP_RANGER_BOOTS(80, "Equip some Ranger Boots", "Equip a pair of Ranger Boots.", LeaguesRegion.GLOBAL),
	EQUIP_GILDED_SET(80, "Equip a Full Gilded Set", "Equip either a full set of Gilded Rune Armour or a full set of Gilded Dragonhide Armour", LeaguesRegion.GLOBAL),
	EQUIP_GOD_DRAGONHIDE_SET(80, "Equip a Full God Dragonhide Set", "Equip a Blessed coif, Body, Chaps, & Bracers with all the pieces aligned to the same god.", LeaguesRegion.GLOBAL),
	EQUIP_GOD_RUNE_SET(80, "Equip a Full God Rune Set", "Equip a full set of God Rune Armour with all the pieces aligned to the same god.", LeaguesRegion.GLOBAL),
	FLETCH_OAK_SHORTBOW(10, "Fletch an Oak Shortbow", "Fletch an Oak Shortbow.", LeaguesRegion.GLOBAL),
	FLETCH_ARROW_SHAFT(10, "Fletch Some Arrow Shafts", "Fletch some Arrow Shafts.", LeaguesRegion.GLOBAL),
	FLETCH_1000_ARROW_SHAFTS(10, "Fletch 1000 Arrow Shafts", "Fletch 1000 Arrow Shafts.", LeaguesRegion.GLOBAL, 0),
	FLETCH_150_IRON_ARROW(10, "Fletch 150 Iron Arrows", "Fletch 150 Iron Arrows.", LeaguesRegion.GLOBAL, 0),
	FLETCH_25_OAK_STOCKS(10, "Fletch 25 Oak Stocks", "Fletch 25 Oak Stocks.", LeaguesRegion.GLOBAL, 0),
	MAKE_ATTACK_POTION(10, "Make an Attack Potion", "Make an Attack Potion.", LeaguesRegion.GLOBAL),
	MINE_10_TIN_ORE(10, "Mine 10 Tin Ore", "Mine 10 Tin Ore.", LeaguesRegion.GLOBAL, 0),
	MINE_15_COAL(10, "Mine 15 Coal", "Mine 15 Coal.", LeaguesRegion.GLOBAL, 0),
	MINE_COPPER_ORE(10, "Mine Some Copper Ore", "Mine some Copper Ore.", LeaguesRegion.GLOBAL),
	MINE_STEEL_PICK(10, "Mine some Ore With a Steel Pickaxe", "Mine any Ore using a Steel Pickaxe.", LeaguesRegion.GLOBAL),
	PICKPOCKET_MAN_WOMAN(10, "Pickpocket a Citizen", "Pickpocket a Man or a Woman", LeaguesRegion.GLOBAL),
	LIGHT_A_TORCH(10, "Light a Torch", "Light a Torch.", LeaguesRegion.GLOBAL),
	MAKE_FLOUR(10, "Make Some Flour", "Make some Flour.", LeaguesRegion.GLOBAL),
	LOCATE_ALTAR(10, "Locate a Runecrafting Altar With a Talisman", "Use any talisman to check the location of a Runecrafting Altar", LeaguesRegion.GLOBAL),
	PLANT_ALLOTMENT(10, "Plant Seeds in an Allotment Patch", "Plant some seeds in an Allotment Patch.", LeaguesRegion.GLOBAL),
	RAKE_PATCH(10, "Rake a Farming Patch", "Rake any Farming Patch.", LeaguesRegion.GLOBAL),
	PROTECT_PATCH(10, "Protect Your Crops", "Pay a farmer to protect any of your crops.", LeaguesRegion.GLOBAL),
	RECEIVE_SLAYER_TASK(10, "Receive a Slayer Task", "Receive a Slayer Task from any Slayer Master.", LeaguesRegion.GLOBAL),
	RESTORE_50_PRAYER_POINTS(10, "Restore 50 Prayer Points at an Altar", "Restore 50 or more Prayer Points at any altar.", LeaguesRegion.GLOBAL),
	RESTORE_750_PRAYER_POINTS(80, "Restore 750 Prayer Points at an Altar", "Restore 750 or more Prayer Points at any altar.", LeaguesRegion.GLOBAL),
	SMELT_BRONZE_BAR(10, "Smelt a Bronze Bar", "Use a Furnace to smelt a Bronze Bar.", LeaguesRegion.GLOBAL),
	SMELT_IRON_BAR(10, "Smelt an Iron Bar", "Use a Furnace to smelt an Iron Bar.", LeaguesRegion.GLOBAL),
	SMELT_STEEL_BAR(40, "Smelt a Steel Bar", "Use a Furnace to smelt a Steel Bar.", LeaguesRegion.GLOBAL),
	SMELT_RUNITE_BAR(80, "Smelt a Runite Bar", "Use a Furnace to smelt a Runite Bar.", LeaguesRegion.GLOBAL),
	SMITH_150_IRON_ARROWHEADS(10, "Smith 150 Iron Arrowheads", "Use an Anvil to smith 150 Iron Arrowheads.", LeaguesRegion.GLOBAL, 0),
	SMITH_BRONZE_HELM(10, "Smith a Bronze Helm", "Use an Anvil to smith a Bronze Helm.", LeaguesRegion.GLOBAL),
	SMITH_BRONZE_PLATESKIRT(10, "Smith a Bronze Plateskirt", "Use an Anvil to smith a Bronze Plateskirt.", LeaguesRegion.GLOBAL),
	SNARE_BIRD(10, "Snare a Bird", "Catch any bird with a Bird Snare.", LeaguesRegion.GLOBAL),
	SPIN_WOOL(10, "Spin a Ball of Wool", "Use a Spinning Wheel to spin a Ball of Wool.", LeaguesRegion.GLOBAL),
	STEAL_CHOCOLATE_SLICE(10, "Steal a Chocolate Slice", "Steal a Chocolate Slice from a Bakery Stall.", LeaguesRegion.GLOBAL),
	STEAL_SILK(10, "Steal Some Silk", "Steal some silk from a silk stall.", LeaguesRegion.GLOBAL),
	CUT_RED_TOPAZ(10, "Successfully Cut a Red Topaz", "Successfully Cut a Red Topaz", LeaguesRegion.GLOBAL),
	SUPERHUMAN_STRENGTH_IMPROVED_REFLEXES(10, "Superhuman Strength and Improved Reflexes", "Use both the Superhuman Strength prayer and the Improved Reflexes prayer at the same time.", LeaguesRegion.GLOBAL),
	SMITE(40, "Activate Smite", "Activate Smite in your Prayer book.", LeaguesRegion.GLOBAL),
	PROTECT_MELEE(40, "Use the Protect from Melee Prayer", "Use the Protect from Melee Prayer.", LeaguesRegion.GLOBAL),
	CHIVALRY(40, "Use the Chivalry Prayer", "Use the Chivalry Prayer.", LeaguesRegion.KANDARIN),
	PIETY(80, "Use the Piety Prayer", "Use the Piety Prayer.", LeaguesRegion.KANDARIN),
	CATCH_BABY_IMPLING(10, "Catch a Baby Impling", "Catch a Baby Impling.", LeaguesRegion.GLOBAL),
	BUILD_ROOM(10, "Build a Room in Your Player Owned House", "Build a room in your Player Owned House.", LeaguesRegion.GLOBAL),
	BIRD_NEST(10, "Obtain a Bird Nest", "Obtain a Bird Nest whilst cutting down trees.", LeaguesRegion.GLOBAL),
	OBTAIN_GEM(10, "Obtain a Gem While Mining", "Obtain any kind of gem whilst Mining a rock.", LeaguesRegion.GLOBAL),
	;

	private final int points;

	private final String name;
	private final String description;

	private final LeaguesRegion region;

	private final Object attributesDefault;

	LeaguesTask(int points, String name, String description, LeaguesRegion region, Object attributesDefault) {
		this.points = points;
		this.name = name;
		this.description = description;
		this.region = region;
		this.attributesDefault = attributesDefault;
	}

	LeaguesTask(int points, String name, String description, LeaguesRegion region) {
		this(points, name, description, region, null);
	}

	public int getPoints() {
		return points;
	}

	public String getName() {
		return name;
	}

	public String getDescription() {
		return description;
	}

	public LeaguesRegion getRegion() {
		return region;
	}

	public Object getAttributesDefault() {
		return attributesDefault;
	}
}
